// Legg til/endre produkter her
const PRODUCTS = [
  {
    id: 'brann-crest',
    name: 'Brann Crest',
    tagline: 'Klassisk klubbemblem',
    description: 'Det klassiske Brann-emblemet i sticker-format. Perfekt for drikkebottle, laptop og tifo-bruk. Slitesterk UV-bestandig vinyl som tåler alt vær.',
    cat: 'klassisk',
    emoji: '🛡️',
    prices: { 50: 249, 100: 399, 200: 649 },
  },
  {
    id: 'ultra-force',
    name: 'Ultra Force',
    tagline: 'Ultras tifo-design',
    description: 'Laget for de hardeste supporterne på Stadion. Kraftig grafisk uttrykk, sort og rød. Viser hvem du heier på – og det er ingen tvil.',
    cat: 'ultras',
    emoji: '🔥',
    prices: { 50: 279, 100: 449, 200: 749 },
  },
  {
    id: 'bergen-proud',
    name: 'Bergen Stolt',
    tagline: 'For hjembyen vår',
    description: 'Brann og Bergen – uatskillelige. Dette designet hyller både klubben og byen vi elsker. Fjordene, regnet og rød-hvitt.',
    cat: 'klassisk',
    emoji: '🏔️',
    prices: { 50: 259, 100: 419, 200: 699 },
  },
  {
    id: 'kamp-dag',
    name: 'Kamp Dag',
    tagline: 'Matchday-stemning',
    description: 'Når det er kamp, er alt annet uvesentlig. Denne stickeren fanger følelsen av kampdag på Brann Stadion.',
    cat: 'kamp',
    emoji: '⚽',
    prices: { 50: 229, 100: 369, 200: 599 },
  },
  {
    id: 'rod-arme',
    name: 'Rød Armé',
    tagline: 'Ultras samleredition',
    description: 'En hyllest til Supporterklubben og all energien på tribunen. Begrenset design – bestill mens du kan.',
    cat: 'ultras',
    emoji: '✊',
    prices: { 50: 299, 100: 499, 200: 849 },
  },
  {
    id: 'tribunen',
    name: 'Tribunen',
    tagline: 'Hjerteslaget til Brann',
    description: 'Tribunen er der magien skjer. Dette designet feirer alle som møter opp, kamp etter kamp, uansett vær.',
    cat: 'kamp',
    emoji: '📣',
    prices: { 50: 239, 100: 389, 200: 629 },
  },
];
